app/__init__.py
from flask import Flask
from .routes.main_routes import main_bp
from flask import url_for

def create_app():
    app = Flask(__name__)
    app.register_blueprint(main_bp)

    return app

app/routes/main_routes.py
from flask import Blueprint, render_template, current_app
import os
import ollama

main_bp = Blueprint("main",__name__,template_folder="templates", static_folder="static")

@main_bp.route("/")
def index():
    return render_template("index.html")

@main_bp.route("/gallerie")
def gallerie():
    file_names = sorted(os.listdir('app/static/img'))
    current_app.logger.info(file_names)
    
    img_path = ['../static/img/' + x for x in file_names]
    current_app.logger.info(img_path)



    ollama.pull('gemma3:12b')
    response = ollama.chat(model='gemma3:12b', 
    messages=[{
        'role': 'user', 
        'content': "Raconte une histoire effrayante en t'inspirant de l'image, l'histoire doit faire 3 phrases.",
        'images': ["app/static/img/4pote.jpg"]
    }],
    # options={"temperature":0.7}
    )

    return render_template("gallerie.html", files_path=img_path, rep=response)


    

app/templates/gallerie.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Histoires imagées</title>
    <link rel="stylesheet" href="{{ url_for('main.static', filename='css/style.css') }}">
    <link rel="icon" href="./favicon.ico" type="image/x-icon">
  </head>
  <body>
    <main>
        <h1 class="maintitre"> Chair de poule</h1> 
        <p>{{ rep['message']['content'] }}</p>
    </main>
    <section>
        <h2>Clique si tu l'oses !</h2>
        <div class="container">
            
            {% for x in files_path %}
            <div class="item">
                <img src="{{ x }}">
            </div>
            {% endfor %}
            

        </div>
    </section>
  </body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Histoires imagées</title>
    <link rel="stylesheet" href="{{ url_for('main.static', filename='css/style.css') }}">
  </head>
  <body>
    <main>
        <h1 class="maintitre">Père Castor, raconte-moi une histoire.</h1> 
        <h2> Oui mon petit, mais il me faut des images !
            <br> Regarde sous mes pieds, une porte magique !
        </h2> 
        <img src="{{ url_for('main.static', filename='img/1hamster.jpg') }}" />
        <p> 
            Au cours de ses fantastiques aventures,
            le doigt enchanteur est doté de plusieurs vies et subit des métamorphoses ; 
            il sait aussi devenir prothèse et se dédoubler en une barre rigide pour glisser sur la guitare jouée à plat : 
            la « lap steel guitare ».
        </p>
        <a class="button1" type="button" href="{{ url_for('main.gallerie')}}"> Pays des merveilles </a>
    </main>
  </body>
</html>